[package]
name = "transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.27"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.128"
tokio = { version = "1", features = ["full"] }
rand = "0.8"